sudo: false
language: node_js
node_js:
  - "node"
before_install:
  - npm i -g npm@5.7.1
  - npm install -g greenkeeper-lockfile@1
  - greenkeeper-lockfile-update
install:
  - npm ci
# keep the npm cache around to speed up installs
cache:
  directories:
    - "$HOME/.npm"
script: npm run travis
after_script: greenkeeper-lockfile-upload
